/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carlosr
 */
public class MainForm extends javax.swing.JFrame {

    
    private OndaPanel ondaPanel;

    
    private GeneradorAudio generador = new GeneradorAudio();
    
    
    
    
   
    //private OndaPanel ondaPanel = new OndaPanel();
    
    
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        

ondaPanel = new OndaPanel();
ondaPanel.setBounds(0, 0, panelGrafica.getWidth(), panelGrafica.getHeight());
panelGrafica.add(ondaPanel);
ondaPanel.repaint();

        
         // Cambios en tiempo real
 /*   sldFrecuencia.addChangeListener(e -> {
        generador.setFrecuencia(sldFrecuencia.getValue());
        lblEstado.setText("Frecuencia: " + sldFrecuencia.getValue() + " Hz");
    });

    sldAmplitud.addChangeListener(e -> {
        generador.setAmplitud(sldAmplitud.getValue());
        lblEstado.setText("Amplitud: " + sldAmplitud.getValue() + "%");
    });*/
        
        
      sldFrecuencia.addChangeListener(e -> {
    double f = sldFrecuencia.getValue();
    generador.setFrecuencia(f);
    ondaPanel.setParametros(f, sldAmplitud.getValue(), cmbTipoOnda.getSelectedItem().toString());
    lblEstado.setText("Frecuencia: " + f + " Hz");
});

sldAmplitud.addChangeListener(e -> {
    double a = sldAmplitud.getValue();
    generador.setAmplitud(a);
    ondaPanel.setParametros(sldFrecuencia.getValue(), a, cmbTipoOnda.getSelectedItem().toString());
    lblEstado.setText("Amplitud: " + a + "%");
});

cmbTipoOnda.addActionListener(e -> {
    String tipo = cmbTipoOnda.getSelectedItem().toString();
    generador.setTipoOnda(tipo);
    ondaPanel.setParametros(sldFrecuencia.getValue(), sldAmplitud.getValue(), tipo);
    lblEstado.setText("Tipo de onda: " + tipo);
    
});  
        
        
           // Cambios en tiempo real
   // Cambios en tiempo real
/*sldFrecuencia.addChangeListener(e -> {
    ondaPanel.setParametros(sldFrecuencia.getValue(), sldAmplitud.getValue(), cmbTipoOnda.getSelectedItem().toString());
    lblEstado.setText("Frecuencia: " + sldFrecuencia.getValue() + " Hz");
});

sldAmplitud.addChangeListener(e -> {
    ondaPanel.setParametros(sldFrecuencia.getValue(), sldAmplitud.getValue(), cmbTipoOnda.getSelectedItem().toString());
    lblEstado.setText("Amplitud: " + sldAmplitud.getValue() + "%");
});

cmbTipoOnda.addActionListener(e -> {
    ondaPanel.setParametros(sldFrecuencia.getValue(), sldAmplitud.getValue(), cmbTipoOnda.getSelectedItem().toString());
    lblEstado.setText("Tipo de onda: " + cmbTipoOnda.getSelectedItem().toString());
});*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrecuencia = new javax.swing.JLabel();
        sldFrecuencia = new javax.swing.JSlider();
        lblAmplitud = new javax.swing.JLabel();
        sldAmplitud = new javax.swing.JSlider();
        lblTipo = new javax.swing.JLabel();
        cmbTipoOnda = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        panelGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFrecuencia.setText("Fecuencia (Hz)");

        sldFrecuencia.setMaximum(2000);
        sldFrecuencia.setMinimum(100);
        sldFrecuencia.setValue(440);

        lblAmplitud.setText("Amplitud");

        lblTipo.setText("Tipo de onda:");

        cmbTipoOnda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senoidal", "Cuadrada", "Triangular", " " }));
        cmbTipoOnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoOndaActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar sonido");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnDetener.setText("Detener");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado:");

        panelGrafica.setName("panelGrafica"); // NOI18N

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrecuencia)
                    .addComponent(sldFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldAmplitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmplitud)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerar)
                                .addGap(42, 42, 42)
                                .addComponent(btnDetener))
                            .addComponent(lblTipo)
                            .addComponent(cmbTipoOnda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblFrecuencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstado)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sldFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblAmplitud)
                        .addGap(31, 31, 31)
                        .addComponent(sldAmplitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipo)
                        .addGap(24, 24, 24)
                        .addComponent(cmbTipoOnda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerar)
                            .addComponent(btnDetener)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoOndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoOndaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoOndaActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
   if (!generador.isReproduciendo()) {
        generador.iniciar();
        lblEstado.setText("Generando...");
    }
//ondaPanel.setParametros(sldFrecuencia.getValue(), sldAmplitud.getValue(), cmbTipoOnda.getSelectedItem().toString());

    // Actualizamos según los sliders
    //generador.setFrecuencia(sldFrecuencia.getValue());
   // generador.setAmplitud(sldAmplitud.getValue());      // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
generador.detener();
    lblEstado.setText("Detenido");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbTipoOnda;
    private javax.swing.JLabel lblAmplitud;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFrecuencia;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JSlider sldAmplitud;
    private javax.swing.JSlider sldFrecuencia;
    // End of variables declaration//GEN-END:variables
}
